export const INITIAL_DATA = {
  stats: {
    patientsToday: 14,
    totalPatients: 142,
    appointmentsToday: 8,
    waitingQueue: 3,
    occupiedBeds: 18,
    totalBeds: 24,
    totalRevenue: 15420.0,
    pendingLabs: 4,
    lowStockDrugs: 3,
    todaySales: 2150.0,
  },
  patients: [
    {
      id: 1,
      mrn: 'MRN-2026-0001',
      name: 'John Doe',
      gender: 'Male',
      age: 38,
      bloodGroup: 'O+',
      phone: '+1 (555) 234-5678',
      allergies: 'Penicillin, NSAIDs',
      condition: 'Hypertension Follow-up',
      token: 'CARD-001',
      time: '09:00 AM',
      status: 'Waiting',
      doctor: 'Dr. Sarah Smith',
    },
    {
      id: 2,
      mrn: 'MRN-2026-0002',
      name: 'Emma Watson',
      gender: 'Female',
      age: 29,
      bloodGroup: 'A+',
      phone: '+1 (555) 876-5432',
      allergies: 'None',
      condition: 'Acute Migraine',
      token: 'CARD-002',
      time: '09:30 AM',
      status: 'In-Consultation',
      doctor: 'Dr. Michael Chen',
    },
    {
      id: 3,
      mrn: 'MRN-2026-0003',
      name: 'Robert Davis',
      gender: 'Male',
      age: 52,
      bloodGroup: 'B+',
      phone: '+1 (555) 345-6789',
      allergies: 'Sulfa Drugs',
      condition: 'Type 2 Diabetes Review',
      token: 'CARD-003',
      time: '10:15 AM',
      status: 'Waiting',
      doctor: 'Dr. Sarah Smith',
    },
    {
      id: 4,
      mrn: 'MRN-2026-0004',
      name: 'Olivia Martinez',
      gender: 'Female',
      age: 41,
      bloodGroup: 'AB+',
      phone: '+1 (555) 901-2345',
      allergies: 'Aspirin',
      condition: 'Post-op Ward Check',
      token: 'CARD-004',
      time: '11:00 AM',
      status: 'Completed',
      doctor: 'Dr. Robert Taylor',
    },
  ],
  beds: [
    { id: 1, number: 'ICU-01', ward: 'Intensive Care Unit (ICU)', status: 'Occupied', patient: 'James Taylor', vitals: 'BP 130/85, SpO2 98%' },
    { id: 2, number: 'ICU-02', ward: 'Intensive Care Unit (ICU)', status: 'Occupied', patient: 'Emily Clark', vitals: 'BP 120/80, SpO2 99%' },
    { id: 3, number: 'ICU-03', ward: 'Intensive Care Unit (ICU)', status: 'Available', patient: null },
    { id: 4, number: 'EM-01', ward: 'Emergency Ward', status: 'Occupied', patient: 'David Miller', vitals: 'BP 145/90, SpO2 96%' },
    { id: 5, number: 'EM-02', ward: 'Emergency Ward', status: 'Available', patient: null },
    { id: 6, number: 'GW-M01', ward: 'Male General Ward', status: 'Occupied', patient: 'Samuel Jackson', vitals: 'BP 118/78, SpO2 99%' },
    { id: 7, number: 'GW-M02', ward: 'Male General Ward', status: 'Available', patient: null },
    { id: 8, number: 'GW-F01', ward: 'Female General Ward', status: 'Occupied', patient: 'Grace Kelly', vitals: 'BP 125/82, SpO2 98%' },
    { id: 9, number: 'VIP-01', ward: 'Private VIP Suite', status: 'Available', patient: null },
  ],
  medicines: [
    { id: 1, name: 'Amoxicillin 500mg', generic: 'Amoxicillin', category: 'Antibiotics', stock: 4, minAlert: 20, price: 12.50 },
    { id: 2, name: 'Paracetamol 500mg', generic: 'Acetaminophen', category: 'Analgesics', stock: 150, minAlert: 50, price: 5.00 },
    { id: 3, name: 'Metformin 850mg', generic: 'Metformin HCl', category: 'Antidiabetic', stock: 8, minAlert: 30, price: 15.00 },
    { id: 4, name: 'Amlodipine 10mg', generic: 'Amlodipine Besylate', category: 'Cardiovascular', stock: 85, minAlert: 25, price: 18.00 },
    { id: 5, name: 'Azithromycin 500mg', generic: 'Azithromycin', category: 'Antibiotics', stock: 6, minAlert: 15, price: 22.00 },
  ],
  labRequests: [
    { id: 1, reqNo: 'LAB-2026-001', patient: 'John Doe', test: 'Complete Blood Count (CBC) + Lipid Profile', priority: 'Urgent', status: 'In Progress' },
    { id: 2, reqNo: 'LAB-2026-002', patient: 'Emma Watson', test: 'HbA1c & Fasting Blood Sugar', priority: 'Routine', status: 'Pending' },
    { id: 3, reqNo: 'LAB-2026-003', patient: 'Robert Davis', test: 'Liver Function Panel (LFT)', priority: 'Routine', status: 'Completed', result: 'All parameters normal' },
  ],
  invoices: [
    { id: 1, invNo: 'INV-2026-001', patient: 'John Doe', amount: 150.00, paid: 150.00, due: 0.00, status: 'Paid', date: '2026-09-30' },
    { id: 2, invNo: 'INV-2026-002', patient: 'Emma Watson', amount: 320.00, paid: 100.00, due: 220.00, status: 'Partial', date: '2026-09-30' },
    { id: 3, invNo: 'INV-2026-003', patient: 'Robert Davis', amount: 480.00, paid: 0.00, due: 480.00, status: 'Unpaid', date: '2026-09-30' },
  ]
};
